### ISSUE TITLE
error test_apps + test_clustering

### ISSUE THREAD

**Issue by francescofenu** [lucabaldini/ixpeobssim#681]
=====================================================================
ERROR: test_clustering (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_clustering
Traceback (most recent call last):
  File "/home/francesco/anaconda3/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/francesco/anaconda3/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/francesco/IXPE/ixpeobssim/tests/test_clustering.py", line 25, in <module>
    from ixpeobssim.evt.display import xL1EventFile, xL1Event
  File "/home/francesco/IXPE/ixpeobssim/ixpeobssim/evt/display.py", line 157, in <module>
    class Recon:
  File "/home/francesco/IXPE/ixpeobssim/ixpeobssim/evt/display.py", line 162, in Recon
    absorption_point : tuple[float, float]
TypeError: 'type' object is not subscriptable

======================================================================
ERROR: test_apps (test_main_handle.TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/francesco/IXPE/ixpeobssim/tests/test_main_handle.py", line 46, in test_apps
    module = import_module(file_path)
  File "/home/francesco/IXPE/ixpeobssim/ixpeobssim/utils/system_.py", line 99, in _import_module_3
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/francesco/IXPE/ixpeobssim/ixpeobssim/bin/xpevtdisplay.py", line 32, in <module>
    from ixpeobssim.evt.display import xL1EventFile, xXpolGrid, xDisplayArgumentParser,\
  File "/home/francesco/IXPE/ixpeobssim/ixpeobssim/evt/display.py", line 157, in <module>
    class Recon:
  File "/home/francesco/IXPE/ixpeobssim/ixpeobssim/evt/display.py", line 162, in Recon
    absorption_point : tuple[float, float]
TypeError: 'type' object is not subscriptable

----------------------------------------------------------------------
Ran 363 tests in 663.420s

FAILED (errors=2, skipped=24)
>>> Closing event file /home/francesco/ixpeobssimdata/toy_gauss_disk_du1.fits...
make[1]: Leaving directory '/home/francesco/IXPE/ixpeobssim/tests'

**Comment by lucabaldini** [comment]
Since we're not using type annotations anywhere else in the ixpeobssim codebase, may I suggest that we remove them from the offending modules altogether?

@francescofenu This looks like a good first issue that you could attack. Would you like to create a branch and make a pull request? I'll be happy to assist you in the process :-)

**Comment by lucabaldini** [comment]
@francescofenu You should have received an invitation to join the repo as a collaborator, so that you can create and edit branches.

**Comment by lucabaldini** [comment]
Shipped in 30.0.1
